export interface GenreDefinition {
  name: string;
  aliases: string[];
  region: string;
  bpmMin: number;
  bpmMax: number;
  bpmTypical: number;
  timeSignature: "4/4" | "3/4" | "6/8" | "5/4" | "7/8" | "12/8";
  primaryInstruments: string[];
  commonLanguages: string[];
  vocalCharacteristics: string;
  productionStyle: string;
  subgenres: string[];
  modelPromptKeywords: string[];
  // aceSupportQuality: how well ACE-Step reproduces this genre's sound.
  // "high" = reliable, "medium" = acceptable, "low" = often misses the mark.
  // Use this to warn users when choosing genres ACE-Step handles poorly.
  aceSupportQuality: "high" | "medium" | "low";
}

export const GENRE_DATABASE: GenreDefinition[] = [

  // ─── WESTERN POP ─────────────────────────────────────────────────────────────
  {
    name: "Pop",
    aliases: ["pop music", "mainstream pop", "contemporary pop"],
    region: "Western",
    bpmMin: 90, bpmMax: 130, bpmTypical: 110,
    timeSignature: "4/4",
    primaryInstruments: ["synthesizer", "electric guitar", "bass", "drums", "piano"],
    commonLanguages: ["English", "Spanish", "Korean", "Japanese"],
    vocalCharacteristics: "melodic, catchy hooks, polished production, wide range",
    productionStyle: "compressed, layered harmonies, four-on-the-floor kick, bright highs",
    subgenres: ["Electropop", "Synth-pop", "Dance-pop", "Indie pop", "Chamber pop"],
    modelPromptKeywords: ["pop music", "catchy melody", "polished production", "radio-ready"],
    aceSupportQuality: "high",
  },
  {
    name: "Synth-pop",
    aliases: ["synthpop", "electronic pop", "new wave"],
    region: "Western",
    bpmMin: 100, bpmMax: 140, bpmTypical: 120,
    timeSignature: "4/4",
    primaryInstruments: ["synthesizer", "drum machine", "bass synth", "vocoder"],
    commonLanguages: ["English", "German", "French"],
    vocalCharacteristics: "clean, slightly detached, sometimes vocoded, minimal vibrato",
    productionStyle: "analog synth pads, sequenced bassline, gated reverb snare, 80s aesthetic",
    subgenres: ["Dark synth", "Chillwave", "Vaporwave", "Retrowave"],
    modelPromptKeywords: ["synthesizer", "electronic pop", "80s synth", "drum machine beats"],
    aceSupportQuality: "high",
  },
  {
    name: "Indie Pop",
    aliases: ["indie", "alternative pop", "lo-fi pop"],
    region: "Western",
    bpmMin: 80, bpmMax: 130, bpmTypical: 105,
    timeSignature: "4/4",
    primaryInstruments: ["acoustic guitar", "electric guitar", "bass", "drums", "piano"],
    commonLanguages: ["English"],
    vocalCharacteristics: "breathy, intimate, slightly raw, conversational phrasing",
    productionStyle: "warm, organic, room ambience, subtle reverb, dynamic range preserved",
    subgenres: ["Dream pop", "Shoegaze", "Chamber pop", "Jangle pop"],
    modelPromptKeywords: ["indie pop", "organic sound", "guitar-driven", "intimate vocals"],
    aceSupportQuality: "high",
  },

  // ─── ROCK ────────────────────────────────────────────────────────────────────
  {
    name: "Rock",
    aliases: ["rock music", "classic rock", "mainstream rock"],
    region: "Western",
    bpmMin: 100, bpmMax: 160, bpmTypical: 130,
    timeSignature: "4/4",
    primaryInstruments: ["electric guitar", "bass guitar", "drums", "vocals"],
    commonLanguages: ["English"],
    vocalCharacteristics: "powerful, gritty, high energy, chest voice dominant",
    productionStyle: "distorted guitars, punchy drums, room mics, mid-forward mix",
    subgenres: ["Classic rock", "Hard rock", "Alternative rock", "Garage rock", "Surf rock"],
    modelPromptKeywords: ["electric guitar", "rock drums", "distortion", "powerful vocals", "live band"],
    aceSupportQuality: "high",
  },
  {
    name: "Metal",
    aliases: ["heavy metal", "hard metal", "extreme metal"],
    region: "Western",
    bpmMin: 120, bpmMax: 220, bpmTypical: 165,
    timeSignature: "4/4",
    primaryInstruments: ["distorted guitar", "bass guitar", "double kick drums", "vocals"],
    commonLanguages: ["English", "German", "Swedish"],
    vocalCharacteristics: "aggressive screaming or operatic singing, wide dynamic range",
    productionStyle: "heavily distorted guitars, triggered drums, scooped mids, wall of sound",
    subgenres: ["Thrash", "Death metal", "Black metal", "Nu-metal", "Doom", "Metalcore"],
    modelPromptKeywords: ["heavy metal", "distorted guitars", "aggressive drums", "intense energy"],
    aceSupportQuality: "medium",
  },
  {
    name: "Punk",
    aliases: ["punk rock", "hardcore punk"],
    region: "Western",
    bpmMin: 140, bpmMax: 200, bpmTypical: 170,
    timeSignature: "4/4",
    primaryInstruments: ["electric guitar", "bass", "drums"],
    commonLanguages: ["English"],
    vocalCharacteristics: "shouted, raw, no polish, rebellious attitude",
    productionStyle: "lo-fi, fast chord changes, minimal production, aggressive energy",
    subgenres: ["Hardcore", "Pop punk", "Skate punk", "Post-punk"],
    modelPromptKeywords: ["punk rock", "fast guitar", "raw energy", "rebellious"],
    aceSupportQuality: "medium",
  },

  // ─── ELECTRONIC & DANCE ──────────────────────────────────────────────────────
  {
    name: "EDM",
    aliases: ["electronic dance music", "dance music", "club music"],
    region: "Western",
    bpmMin: 120, bpmMax: 150, bpmTypical: 128,
    timeSignature: "4/4",
    primaryInstruments: ["synthesizer", "drum machine", "bass synth", "sampler"],
    commonLanguages: ["English"],
    vocalCharacteristics: "chopped and filtered, hooks designed for drops, anthemic",
    productionStyle: "four-on-the-floor kick, sidechain compression, buildups and drops, supersaw leads",
    subgenres: ["Progressive house", "Big room", "Electro house", "Dubstep", "Trap EDM"],
    modelPromptKeywords: ["EDM", "electronic dance", "four-on-the-floor", "synthesizer drop", "club music"],
    aceSupportQuality: "high",
  },
  {
    name: "House",
    aliases: ["house music", "deep house", "chicago house"],
    region: "Western",
    bpmMin: 120, bpmMax: 135, bpmTypical: 125,
    timeSignature: "4/4",
    primaryInstruments: ["Roland TR-909 drum machine", "synthesizer", "piano", "bass"],
    commonLanguages: ["English"],
    vocalCharacteristics: "soulful, gospel-inflected, looped vocal chops",
    productionStyle: "four-on-the-floor kick, offbeat hi-hats, warm bass, lush chords",
    subgenres: ["Deep house", "Tech house", "Afro house", "Jackin house", "Vocal house"],
    modelPromptKeywords: ["house music", "four-on-the-floor", "soulful", "warm bass", "piano chords"],
    aceSupportQuality: "high",
  },
  {
    name: "Techno",
    aliases: ["techno music", "detroit techno", "industrial techno"],
    region: "Western",
    bpmMin: 130, bpmMax: 160, bpmTypical: 140,
    timeSignature: "4/4",
    primaryInstruments: ["drum machine", "synthesizer", "bass synth"],
    commonLanguages: [],
    vocalCharacteristics: "minimal or no vocals, sometimes robotic samples",
    productionStyle: "mechanical repetition, heavy kick, layered percussion, industrial textures",
    subgenres: ["Minimal techno", "Industrial techno", "Dub techno", "Acid techno"],
    modelPromptKeywords: ["techno", "mechanical drums", "industrial", "repetitive", "dark electronic"],
    aceSupportQuality: "medium",
  },
  {
    name: "Ambient",
    aliases: ["ambient music", "atmospheric music", "soundscape"],
    region: "Western",
    bpmMin: 50, bpmMax: 90, bpmTypical: 70,
    timeSignature: "4/4",
    primaryInstruments: ["synthesizer pads", "piano", "field recordings", "guitar with effects"],
    commonLanguages: [],
    vocalCharacteristics: "wordless vocals, heavily processed, ethereal textures",
    productionStyle: "long reverbs, slow evolution, no percussion or very subtle, spatial",
    subgenres: ["Dark ambient", "Space ambient", "Nature ambient", "Drone"],
    modelPromptKeywords: ["ambient", "atmospheric", "pads", "ethereal", "slow evolution", "spacious"],
    aceSupportQuality: "medium",
  },
  {
    name: "Drum and Bass",
    aliases: ["DnB", "D&B", "jungle"],
    region: "Western",
    bpmMin: 160, bpmMax: 180, bpmTypical: 174,
    timeSignature: "4/4",
    primaryInstruments: ["drum machine", "bass synth", "synthesizer"],
    commonLanguages: ["English"],
    vocalCharacteristics: "MC-style rapid fire, soulful hooks sampled",
    productionStyle: "breakbeat at 170+ BPM, heavy sub-bass, syncopated rhythms",
    subgenres: ["Liquid DnB", "Neurofunk", "Jump-up", "Techstep"],
    modelPromptKeywords: ["drum and bass", "breakbeat", "fast drums", "sub-bass", "170 BPM"],
    aceSupportQuality: "medium",
  },
  {
    name: "Lo-fi",
    aliases: ["lo-fi hip hop", "chill lo-fi", "study music"],
    region: "Western",
    bpmMin: 70, bpmMax: 95, bpmTypical: 82,
    timeSignature: "4/4",
    primaryInstruments: ["piano", "jazz guitar", "vinyl samples", "soft drums"],
    commonLanguages: [],
    vocalCharacteristics: "muffled, distant, chopped samples, rarely full vocals",
    productionStyle: "vinyl crackle, tape saturation, off-grid timing, warm filters",
    subgenres: ["Lo-fi hip hop", "Chillhop", "Jazz hop"],
    modelPromptKeywords: ["lo-fi", "vinyl crackle", "warm piano", "relaxed beats", "chill"],
    aceSupportQuality: "high",
  },
  {
    name: "Synthwave",
    aliases: ["retrowave", "outrun", "80s electronic"],
    region: "Western",
    bpmMin: 100, bpmMax: 130, bpmTypical: 115,
    timeSignature: "4/4",
    primaryInstruments: ["analog synthesizer", "drum machine", "bass synth", "guitar"],
    commonLanguages: ["English"],
    vocalCharacteristics: "clean, emotional, reverb-drenched, 80s style",
    productionStyle: "gated reverb, analog warmth, arpeggiated synths, neon aesthetic",
    subgenres: ["Darksynth", "Spacewave", "Vaporwave", "Cyberpunk"],
    modelPromptKeywords: ["synthwave", "retrowave", "80s synths", "neon", "analog warmth"],
    aceSupportQuality: "high",
  },

  // ─── HIP HOP & RAP ───────────────────────────────────────────────────────────
  {
    name: "Hip Hop",
    aliases: ["hip-hop", "rap", "boom bap"],
    region: "Western",
    bpmMin: 80, bpmMax: 100, bpmTypical: 90,
    timeSignature: "4/4",
    primaryInstruments: ["drum machine", "sampler", "bass", "piano"],
    commonLanguages: ["English", "Spanish"],
    vocalCharacteristics: "rhythmic spoken word, syncopated phrasing, complex rhyme schemes",
    productionStyle: "sampled breaks, boom bap drums, chopped soul loops",
    subgenres: ["Boom bap", "Conscious hip hop", "Trap", "Cloud rap", "Mumble rap"],
    modelPromptKeywords: ["hip hop", "rap beat", "boom bap", "sampled drums", "bass groove"],
    aceSupportQuality: "high",
  },
  {
    name: "Trap",
    aliases: ["trap music", "Atlanta trap", "modern trap"],
    region: "Western",
    bpmMin: 120, bpmMax: 145, bpmTypical: 140,
    timeSignature: "4/4",
    primaryInstruments: ["808 bass", "hi-hat rolls", "snare", "synthesizer"],
    commonLanguages: ["English"],
    vocalCharacteristics: "auto-tuned singing/rapping, melodic hooks, ad-libs",
    productionStyle: "triplet hi-hats, rolling 808s, dark melodies, heavy reverb on snare",
    subgenres: ["Melodic trap", "Plugg", "SoundCloud rap", "Rage"],
    modelPromptKeywords: ["trap", "808 bass", "hi-hat rolls", "auto-tune", "dark melodic"],
    aceSupportQuality: "high",
  },
  {
    name: "Drill",
    aliases: ["UK drill", "Chicago drill", "Brooklyn drill"],
    region: "Western",
    bpmMin: 140, bpmMax: 150, bpmTypical: 144,
    timeSignature: "4/4",
    primaryInstruments: ["808 bass", "sliding samples", "piano", "strings"],
    commonLanguages: ["English"],
    vocalCharacteristics: "monotone rap delivery, UK slang, aggressive storytelling",
    productionStyle: "sample chops with pitch bends, sliding 808s, haunting melodies, dark minor key",
    subgenres: ["UK drill", "Chicago drill", "Brooklyn drill", "NY drill"],
    modelPromptKeywords: ["drill music", "dark minor melody", "sliding 808", "aggressive rap", "piano stabs"],
    aceSupportQuality: "high",
  },
  {
    name: "Phonk",
    aliases: ["Memphis phonk", "drift phonk", "cowbell phonk"],
    region: "Western",
    bpmMin: 130, bpmMax: 155, bpmTypical: 145,
    timeSignature: "4/4",
    primaryInstruments: ["808 bass", "cowbell", "old school rap samples", "distorted kick"],
    commonLanguages: ["English"],
    vocalCharacteristics: "chopped Memphis rap vocals, lo-fi vocal samples",
    productionStyle: "distorted 808s, cowbell pattern, chopped vocals, Memphis underground aesthetic",
    subgenres: ["Drift phonk", "Cowbell phonk", "Dark phonk"],
    modelPromptKeywords: ["phonk", "Memphis rap", "cowbell", "dark distorted 808", "chopped samples"],
    aceSupportQuality: "medium",
  },

  // ─── R&B & SOUL ──────────────────────────────────────────────────────────────
  {
    name: "R&B",
    aliases: ["rhythm and blues", "contemporary R&B", "rnb"],
    region: "Western",
    bpmMin: 65, bpmMax: 100, bpmTypical: 80,
    timeSignature: "4/4",
    primaryInstruments: ["piano", "bass", "drums", "synthesizer", "guitar"],
    commonLanguages: ["English"],
    vocalCharacteristics: "melismatic, soulful, expressive runs, falsetto, gospel influence",
    productionStyle: "lush chords, smooth bass groove, layered harmonies, neo-soul warmth",
    subgenres: ["Neo-soul", "Alternative R&B", "Quiet storm", "New jack swing"],
    modelPromptKeywords: ["R&B", "soulful vocals", "smooth groove", "lush harmonies", "neo-soul"],
    aceSupportQuality: "high",
  },
  {
    name: "Soul",
    aliases: ["soul music", "classic soul", "southern soul"],
    region: "Western",
    bpmMin: 65, bpmMax: 110, bpmTypical: 90,
    timeSignature: "4/4",
    primaryInstruments: ["piano", "organ", "brass section", "bass", "drums"],
    commonLanguages: ["English"],
    vocalCharacteristics: "gospel-rooted, raw emotion, powerful belting, call and response",
    productionStyle: "Motown arrangement, horn punches, church organ, live band feel",
    subgenres: ["Motown", "Southern soul", "Chicago soul", "Blue-eyed soul"],
    modelPromptKeywords: ["soul music", "gospel", "organ", "brass section", "emotional vocals"],
    aceSupportQuality: "high",
  },
  {
    name: "Funk",
    aliases: ["funk music", "classic funk"],
    region: "Western",
    bpmMin: 90, bpmMax: 120, bpmTypical: 105,
    timeSignature: "4/4",
    primaryInstruments: ["bass guitar", "drums", "guitar", "brass", "organ"],
    commonLanguages: ["English"],
    vocalCharacteristics: "percussive, rhythmic, groovy, call and response",
    productionStyle: "syncopated bass and drums locked together, guitar chops, horn stabs",
    subgenres: ["P-funk", "Funk rock", "Go-go", "Boogie"],
    modelPromptKeywords: ["funk", "syncopated bass", "guitar chops", "horn stabs", "groove"],
    aceSupportQuality: "medium",
  },

  // ─── JAZZ & BLUES ────────────────────────────────────────────────────────────
  {
    name: "Jazz",
    aliases: ["jazz music", "modern jazz", "traditional jazz"],
    region: "Western",
    bpmMin: 60, bpmMax: 200, bpmTypical: 130,
    timeSignature: "4/4",
    primaryInstruments: ["piano", "double bass", "drums", "trumpet", "saxophone"],
    commonLanguages: ["English"],
    vocalCharacteristics: "scat, swing phrasing, improvised, intimate",
    productionStyle: "swing rhythm, walking bass, brushed drums, improvisational solos",
    subgenres: ["Bebop", "Cool jazz", "Fusion", "Smooth jazz", "Bossa nova", "Swing"],
    modelPromptKeywords: ["jazz", "swing rhythm", "improvisation", "piano trio", "saxophone"],
    aceSupportQuality: "medium",
  },
  {
    name: "Blues",
    aliases: ["blues music", "electric blues", "delta blues"],
    region: "Western",
    bpmMin: 60, bpmMax: 120, bpmTypical: 90,
    timeSignature: "12/8",
    primaryInstruments: ["electric guitar", "harmonica", "piano", "bass", "drums"],
    commonLanguages: ["English"],
    vocalCharacteristics: "raw, emotional, call and response, bent notes, slides",
    productionStyle: "twelve-bar blues form, shuffled rhythm, guitar bends, dirty tone",
    subgenres: ["Delta blues", "Chicago blues", "Texas blues", "Jump blues"],
    modelPromptKeywords: ["blues", "twelve bar", "guitar bends", "harmonica", "shuffle rhythm"],
    aceSupportQuality: "medium",
  },
  {
    name: "Classical",
    aliases: ["classical music", "orchestral", "symphonic"],
    region: "Western",
    bpmMin: 40, bpmMax: 180, bpmTypical: 100,
    timeSignature: "4/4",
    primaryInstruments: ["strings", "woodwinds", "brass", "piano", "percussion"],
    commonLanguages: [],
    vocalCharacteristics: "operatic, trained classical soprano to bass, no amplification",
    productionStyle: "acoustic orchestral recording, dynamic range, concert hall reverb",
    subgenres: ["Baroque", "Romantic", "Modern classical", "Minimalist", "Neo-classical"],
    modelPromptKeywords: ["orchestral", "classical", "strings", "concert hall", "dynamic"],
    aceSupportQuality: "low",
  },
  {
    name: "Folk",
    aliases: ["folk music", "acoustic folk", "americana"],
    region: "Western",
    bpmMin: 70, bpmMax: 120, bpmTypical: 95,
    timeSignature: "4/4",
    primaryInstruments: ["acoustic guitar", "banjo", "fiddle", "harmonica", "upright bass"],
    commonLanguages: ["English"],
    vocalCharacteristics: "natural, storytelling, close mic, no heavy processing",
    productionStyle: "acoustic warmth, minimal production, real room sound, no click track",
    subgenres: ["Americana", "Celtic folk", "Contemporary folk", "Bluegrass"],
    modelPromptKeywords: ["folk music", "acoustic guitar", "storytelling", "organic", "fingerpicking"],
    aceSupportQuality: "medium",
  },
  {
    name: "Country",
    aliases: ["country music", "modern country", "Nashville"],
    region: "Western",
    bpmMin: 80, bpmMax: 130, bpmTypical: 105,
    timeSignature: "4/4",
    primaryInstruments: ["acoustic guitar", "pedal steel", "fiddle", "bass", "drums"],
    commonLanguages: ["English"],
    vocalCharacteristics: "twang, storytelling, Southern accent, heartfelt delivery",
    productionStyle: "pedal steel warmth, acoustic guitar strumming, Nashville sound",
    subgenres: ["Classic country", "Country pop", "Outlaw country", "Bro country"],
    modelPromptKeywords: ["country music", "pedal steel", "acoustic guitar", "twang", "Nashville"],
    aceSupportQuality: "medium",
  },

  // ─── REGGAE & CARIBBEAN ──────────────────────────────────────────────────────
  {
    name: "Reggae",
    aliases: ["reggae music", "roots reggae", "jamaican"],
    region: "Caribbean",
    bpmMin: 65, bpmMax: 90, bpmTypical: 75,
    timeSignature: "4/4",
    primaryInstruments: ["guitar", "bass", "organ", "drums", "horns"],
    commonLanguages: ["English", "Jamaican Patois"],
    vocalCharacteristics: "laid-back, melodic, Jamaican accent, message-driven",
    productionStyle: "offbeat guitar skank, heavy bass, one-drop drum pattern, dub effects",
    subgenres: ["Roots reggae", "Dancehall", "Dub", "Ska", "Rocksteady"],
    modelPromptKeywords: ["reggae", "offbeat rhythm", "heavy bass", "jamaican", "roots"],
    aceSupportQuality: "medium",
  },
  {
    name: "Dancehall",
    aliases: ["dancehall music", "bashment"],
    region: "Caribbean",
    bpmMin: 90, bpmMax: 120, bpmTypical: 100,
    timeSignature: "4/4",
    primaryInstruments: ["digital riddim", "drum machine", "bass"],
    commonLanguages: ["Jamaican Patois", "English"],
    vocalCharacteristics: "toasting, deejay-style, rapid fire phrasing, patois",
    productionStyle: "electronic riddims, digital drums, skanking bass, digital production",
    subgenres: ["Ragga", "Digital dancehall", "Lovers rock"],
    modelPromptKeywords: ["dancehall", "riddim", "jamaican patois", "deejay style", "electronic bass"],
    aceSupportQuality: "medium",
  },

  // ─── LATIN ───────────────────────────────────────────────────────────────────
  {
    name: "Latin Pop",
    aliases: ["latin music", "pop latino"],
    region: "Latin",
    bpmMin: 90, bpmMax: 130, bpmTypical: 110,
    timeSignature: "4/4",
    primaryInstruments: ["guitar", "piano", "bass", "percussion", "brass"],
    commonLanguages: ["Spanish", "Portuguese", "English"],
    vocalCharacteristics: "passionate, melodic, Spanish phrasing, expressive",
    productionStyle: "modern production with Latin rhythmic elements, crossover appeal",
    subgenres: ["Reggaeton", "Bachata", "Cumbia pop", "Tropical pop"],
    modelPromptKeywords: ["latin pop", "spanish vocals", "rhythmic", "passionate", "tropical"],
    aceSupportQuality: "high",
  },
  {
    name: "Reggaeton",
    aliases: ["reggaeton music", "perreo", "urbano"],
    region: "Latin",
    bpmMin: 90, bpmMax: 100, bpmTypical: 95,
    timeSignature: "4/4",
    primaryInstruments: ["dembow beat", "bass", "synthesizer", "sampler"],
    commonLanguages: ["Spanish"],
    vocalCharacteristics: "urban Spanish, rap and singing blend, streetwise, explicit",
    productionStyle: "dembow rhythm (kick and snare on every beat), dark basslines, 808s",
    subgenres: ["Old school reggaeton", "Modern reggaeton", "Trapeton", "Champeta"],
    modelPromptKeywords: ["reggaeton", "dembow", "spanish urbano", "perreo beat", "latin trap"],
    aceSupportQuality: "high",
  },
  {
    name: "Salsa",
    aliases: ["salsa music", "cuban salsa", "new york salsa"],
    region: "Latin",
    bpmMin: 160, bpmMax: 220, bpmTypical: 185,
    timeSignature: "4/4",
    primaryInstruments: ["clave", "congas", "piano", "bass", "brass section", "timbales"],
    commonLanguages: ["Spanish"],
    vocalCharacteristics: "passionate, Cuban inflection, shouted chorus, son clave feel",
    productionStyle: "clave rhythm backbone, horn arrangements, montuno piano, call and response",
    subgenres: ["Salsa dura", "Salsa romantica", "Timba"],
    modelPromptKeywords: ["salsa", "clave rhythm", "brass horns", "cuban percussion", "hot dance"],
    aceSupportQuality: "low",
  },
  {
    name: "Bossa Nova",
    aliases: ["bossa nova music", "brazilian jazz"],
    region: "Latin",
    bpmMin: 100, bpmMax: 130, bpmTypical: 115,
    timeSignature: "4/4",
    primaryInstruments: ["nylon string guitar", "piano", "bass", "light percussion"],
    commonLanguages: ["Portuguese", "English"],
    vocalCharacteristics: "breathy, intimate, slightly behind beat, sophisticated",
    productionStyle: "syncopated samba-jazz guitar, gentle bass, brushed percussion, airy",
    subgenres: ["Traditional bossa nova", "Contemporary bossa nova"],
    modelPromptKeywords: ["bossa nova", "nylon guitar", "brazilian", "intimate", "jazz-samba"],
    aceSupportQuality: "medium",
  },

  // ─── AFRICAN ─────────────────────────────────────────────────────────────────
  {
    name: "Afrobeats",
    aliases: ["afrobeats music", "afropop", "afroswing"],
    region: "African",
    bpmMin: 90, bpmMax: 115, bpmTypical: 102,
    timeSignature: "4/4",
    primaryInstruments: ["percussion", "bass", "synthesizer", "guitar", "drums"],
    commonLanguages: ["English", "Yoruba", "Pidgin", "Hausa", "Swahili"],
    vocalCharacteristics: "melodic, rhythmic, West African phrasing, call and response",
    productionStyle: "layered percussion, syncopated groove, talking drum influence, warm bass",
    subgenres: ["Afro-fusion", "Afro-pop", "Afroswing", "Afrobeats UK"],
    modelPromptKeywords: ["afrobeats", "west african percussion", "melodic groove", "rhythmic", "warm bass"],
    aceSupportQuality: "medium",
  },
  {
    name: "Amapiano",
    aliases: ["south african house", "piano music"],
    region: "African",
    bpmMin: 100, bpmMax: 116, bpmTypical: 110,
    timeSignature: "4/4",
    primaryInstruments: ["log drum bass", "piano", "marimba", "percussion"],
    commonLanguages: ["Zulu", "Sotho", "English", "Xhosa"],
    vocalCharacteristics: "South African phrasing, melodic, gospel influence",
    productionStyle: "log drum bassline, marimba leads, syncopated percussion",
    subgenres: ["Piano music", "Amapiano deep", "Amapiano afro fusion"],
    modelPromptKeywords: ["amapiano", "log drum bass", "south african", "marimba", "piano groove"],
    aceSupportQuality: "low",
  },

  // ─── SOUTH ASIAN ─────────────────────────────────────────────────────────────
  {
    name: "Bollywood",
    aliases: ["bollywood music", "hindi film music", "indian pop"],
    region: "South Asian",
    bpmMin: 70, bpmMax: 160, bpmTypical: 110,
    timeSignature: "4/4",
    primaryInstruments: ["tabla", "sitar", "synthesizer", "strings", "bass", "dhol"],
    commonLanguages: ["Hindi", "Urdu"],
    vocalCharacteristics: "ornamental, emotional, melismatic, wide range, classical influence",
    productionStyle: "orchestral strings, electronic production, tabla patterns, dramatic dynamics",
    subgenres: ["Bollywood classical", "Bollywood pop", "Bollywood sad song", "Bollywood party"],
    modelPromptKeywords: ["bollywood", "hindi film music", "tabla", "orchestral strings", "emotional hindi vocals"],
    aceSupportQuality: "medium",
  },
  {
    name: "Bhangra",
    aliases: ["bhangra music", "punjabi folk", "classic bhangra"],
    region: "South Asian",
    bpmMin: 130, bpmMax: 170, bpmTypical: 150,
    timeSignature: "4/4",
    primaryInstruments: ["dhol", "tumbi", "algoza", "chimta", "bass"],
    commonLanguages: ["Punjabi"],
    vocalCharacteristics: "powerful, celebratory, call and response, high energy Punjabi",
    productionStyle: "dhol as backbone, tumbi leads, call and response choruses, festival energy",
    subgenres: ["Classic bhangra", "Modern bhangra", "Bhangra fusion"],
    modelPromptKeywords: ["bhangra", "dhol drums", "tumbi", "punjabi", "celebratory", "high energy"],
    aceSupportQuality: "medium",
  },
  {
    name: "Punjabi Pop",
    aliases: ["punjabi music", "pollywood", "desi pop"],
    region: "South Asian",
    bpmMin: 100, bpmMax: 145, bpmTypical: 120,
    timeSignature: "4/4",
    primaryInstruments: ["dhol", "synthesizer", "bass", "guitar", "tabla"],
    commonLanguages: ["Punjabi", "English"],
    vocalCharacteristics: "melodic, romantic, Punjabi accent, male or female, emotional",
    productionStyle: "modern electronic production fused with dhol and traditional elements",
    subgenres: ["Punjabi romantic", "Punjabi folk pop", "Punjabi sad song"],
    modelPromptKeywords: ["punjabi pop", "desi pop", "dhol beat", "punjabi vocals", "modern indian"],
    aceSupportQuality: "medium",
  },
  {
    name: "Punjabi Drill",
    aliases: ["punjabi drill music", "desi drill", "punjabi trap"],
    region: "South Asian",
    bpmMin: 138, bpmMax: 148, bpmTypical: 142,
    timeSignature: "4/4",
    primaryInstruments: ["808 bass", "sliding samples", "dhol elements", "piano", "strings"],
    commonLanguages: ["Punjabi", "English"],
    vocalCharacteristics: "mix of Punjabi rap and melody, street Punjabi slang, UK/CA accent",
    productionStyle: "UK drill production fused with Punjabi melodies, sliding 808s, dark piano",
    subgenres: ["UK Punjabi drill", "Canadian Punjabi drill", "Indo drill"],
    modelPromptKeywords: ["punjabi drill", "desi drill", "808 bass", "punjabi rap", "dark melody drill"],
    aceSupportQuality: "medium",
  },
  {
    name: "Desi Hip Hop",
    aliases: ["desi rap", "indian hip hop", "hindi rap"],
    region: "South Asian",
    bpmMin: 80, bpmMax: 110, bpmTypical: 92,
    timeSignature: "4/4",
    primaryInstruments: ["808", "sampled tabla", "synthesizer", "bass"],
    commonLanguages: ["Hindi", "Punjabi", "Urdu", "Bengali", "English"],
    vocalCharacteristics: "multilingual rap, hindi/punjabi codemixing, urban storytelling",
    productionStyle: "Western hip hop base with Indian sample flips, tabla pattern integration",
    subgenres: ["Mumbai hip hop", "Gully rap", "Punjabi rap"],
    modelPromptKeywords: ["desi hip hop", "hindi rap", "indian trap", "gully rap", "urban india"],
    aceSupportQuality: "medium",
  },

  // ─── K-POP & EAST ASIAN ──────────────────────────────────────────────────────
  {
    name: "K-Pop",
    aliases: ["kpop", "korean pop", "korean music"],
    region: "East Asian",
    bpmMin: 95, bpmMax: 145, bpmTypical: 120,
    timeSignature: "4/4",
    primaryInstruments: ["synthesizer", "digital drums", "bass", "electronic production"],
    commonLanguages: ["Korean", "English"],
    vocalCharacteristics: "highly trained, precise, harmonized, emotional, dance section delivery",
    productionStyle: "hyper-polished, layered vocal harmonies, dynamic drops, idol group arrangement",
    subgenres: ["K-pop ballad", "K-pop dance", "K-pop R&B", "K-pop hip hop"],
    modelPromptKeywords: ["k-pop", "korean pop", "polished production", "idol group", "chorus drop"],
    aceSupportQuality: "high",
  },
  {
    name: "J-Pop",
    aliases: ["jpop", "japanese pop", "japanese music"],
    region: "East Asian",
    bpmMin: 90, bpmMax: 135, bpmTypical: 112,
    timeSignature: "4/4",
    primaryInstruments: ["synthesizer", "guitar", "bass", "drums", "strings"],
    commonLanguages: ["Japanese", "English"],
    vocalCharacteristics: "high and light, cute or emotional, anime influence",
    productionStyle: "melodic, bright, sometimes dramatic, anime soundtrack feel",
    subgenres: ["J-pop ballad", "Anime song", "City pop", "Shibuya-kei"],
    modelPromptKeywords: ["j-pop", "japanese pop", "anime", "bright melody", "emotional"],
    aceSupportQuality: "high",
  },

  // ─── MIDDLE EASTERN ──────────────────────────────────────────────────────────
  {
    name: "Arabic Pop",
    aliases: ["arabic music", "middle eastern pop", "khaleeji"],
    region: "Middle Eastern",
    bpmMin: 80, bpmMax: 120, bpmTypical: 100,
    timeSignature: "4/4",
    primaryInstruments: ["oud", "qanun", "darbuka", "violin", "synthesizer"],
    commonLanguages: ["Arabic", "English"],
    vocalCharacteristics: "maqam ornamentation, melismatic runs, emotional, quarter tones",
    productionStyle: "maqam modal scales, oud and electronic blend, darbuka percussion",
    subgenres: ["Khaleeji", "Egyptian pop", "Levantine pop", "Arabic R&B"],
    modelPromptKeywords: ["arabic pop", "oud", "maqam", "middle eastern", "ornamental vocals"],
    aceSupportQuality: "low",
  },
];

export function findGenreByName(name: string): GenreDefinition | null {
  const lower = name.toLowerCase();
  return GENRE_DATABASE.find(g =>
    g.name.toLowerCase() === lower ||
    g.aliases.some(a => a.toLowerCase() === lower)
  ) ?? null;
}

export function getGenresByRegion(region: string): GenreDefinition[] {
  return GENRE_DATABASE.filter(g => g.region === region);
}

export function getGenresByLanguage(language: string): GenreDefinition[] {
  return GENRE_DATABASE.filter(g => g.commonLanguages.includes(language));
}

export function GENRE_NAMES(): string[] {
  return GENRE_DATABASE.map(g => g.name);
}

// Returns a UI warning string when ACE-Step quality for a genre is low or medium.
// Show this warning below the genre field when the user selects a problematic genre.
export function getModelQualityWarning(genre: string): string | null {
  const def = findGenreByName(genre);
  if (!def) return null;
  if (def.aceSupportQuality === "low") {
    return `Note: AI generation of ${genre} music is experimental. Results may vary significantly. Consider using Stable Audio (instrumental) for better results.`;
  }
  if (def.aceSupportQuality === "medium") {
    return `Note: ${genre} generation quality is good but not perfect. Results may not fully capture genre nuances.`;
  }
  return null;
}
