export interface LanguageDefinition {
  name: string;
  nativeScript: string;
  aceSupportTier: "primary" | "supported" | "limited";
  minimaxSupport: boolean;
  elevenLabsMultilingualSupport: boolean;
  preferredPath: "elevenlabs-music" | "tts-mix" | "ace-step" | "limited";
  syllableDensity: number;
  codemixPartners: string[];
  associatedGenres: string[];
  lyricsPromptInstruction: string;
  exampleCodemix: string;
}

export const LANGUAGE_DATABASE: LanguageDefinition[] = [
  { name: "Punjabi", nativeScript: "Gurmukhi / Shahmukhi", aceSupportTier: "supported", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "tts-mix", syllableDensity: 1.0, codemixPartners: ["English"], associatedGenres: ["Bhangra", "Punjabi Pop", "Punjabi Drill", "Desi Hip Hop"], lyricsPromptInstruction: "Write primarily in Punjabi using romanized transliteration. Natural codemixing with English is expected as is standard in modern Punjabi pop, bhangra, and drill. At least 65-75% of words must be Punjabi. Common Punjabi words: dil (heart), yaar (friend), saanu (to us), kudi (girl), munda (boy), nachna (to dance), pyaar (love), sohna/sohni (beautiful), rabba (God), wah (wow), oye (hey), tenu (you), menu (me), teri (your), meri (my), raat (night), subah (morning), ishq (love/longing). Do NOT write English with one Punjabi word inserted. The rhythm must feel authentically Punjabi.", exampleCodemix: "Tu meri jaan hai baby, dil tera deewana, let's go yaar, nachdi jaave" },
  { name: "Hindi", nativeScript: "Devanagari", aceSupportTier: "primary", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "tts-mix", syllableDensity: 1.1, codemixPartners: ["English"], associatedGenres: ["Bollywood", "Desi Hip Hop", "Hindi Pop"], lyricsPromptInstruction: "Write primarily in Hindi using romanized transliteration. Natural Hindi-English codemixing (Hinglish) is standard in modern Bollywood and Desi pop. At least 60% Hindi. Common words: dil, pyaar, mohabbat, yaar, zindagi, kabhi, teri, meri, hum, tum, aaj, raat, khwaab, ishq, chand, sitare, aankhein, dard, khushi, yaad.", exampleCodemix: "Dil mera dhadak raha, you make my heart race, tere bina incomplete" },
  { name: "Urdu", nativeScript: "Nastaliq script", aceSupportTier: "supported", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "tts-mix", syllableDensity: 1.1, codemixPartners: ["English", "Hindi"], associatedGenres: ["Ghazal", "Qawwali", "Urdu Pop", "Pakistani Pop"], lyricsPromptInstruction: "Write in Urdu using romanized transliteration. Urdu poetry values beautiful imagery and metaphor. Words: ishq, wafa, junoon, dard, ulfat, tamanna, rooh, subah, shaam, aankhein, gulshan, parwana, shamma, zanjeer. Maintain poetic Urdu rhythm.", exampleCodemix: "Ishq mein dooba hoon main, lost in your eyes, tere bina kuch bhi nahi" },
  { name: "Bengali", nativeScript: "Bengali script", aceSupportTier: "supported", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "tts-mix", syllableDensity: 1.2, codemixPartners: ["English"], associatedGenres: ["Bangla Pop", "Rabindra Sangeet", "Bangla Rock"], lyricsPromptInstruction: "Write in Bengali using romanized transliteration. Bengali music has a rich literary tradition. Common words: aamar (my), bhalo (love/good), basha (home/love), mon (heart/mind), premer (of love), tomar (your), shona (gold/dear), raat (night), akash (sky), nadi (river).", exampleCodemix: "Aamar mon tomar kache, my heart belongs to you, bhalobashar gaan gai" },
  { name: "Tamil", nativeScript: "Tamil script", aceSupportTier: "supported", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "tts-mix", syllableDensity: 1.3, codemixPartners: ["English"], associatedGenres: ["Tamil Pop", "Kollywood", "Tamil Folk"], lyricsPromptInstruction: "Write in Tamil using romanized transliteration. Words: en (my), nee (you), kadhal (love), vaanam (sky), manasu (heart), azhagu (beauty), nenjam (heart/chest), uyire (life/soul). Tamil lyrics have melodic cadence — keep lines short and rhythmic.", exampleCodemix: "En manasu nee thaan, you are my everything, kadhal konjam crazy" },
  { name: "Telugu", nativeScript: "Telugu script", aceSupportTier: "supported", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "tts-mix", syllableDensity: 1.3, codemixPartners: ["English"], associatedGenres: ["Tollywood", "Telugu Pop", "Telugu Folk"], lyricsPromptInstruction: "Write in Telugu using romanized transliteration. Words: nee (your), nenu (I), premalo (in love), manasu (heart), akasam (sky), prema (love), navvulu (smiles), kallu (eyes), gundelu (heart). Use vowel-rich words for melodic flow.", exampleCodemix: "Nee kallalo prema chusa, fell in love with your eyes, manasu maatladutondi" },
  { name: "Arabic", nativeScript: "Arabic script", aceSupportTier: "supported", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "tts-mix", syllableDensity: 0.9, codemixPartners: ["English", "French"], associatedGenres: ["Arabic Pop", "Khaleeji", "Raï", "Arabic Hip Hop"], lyricsPromptInstruction: "Write in Arabic using romanized transliteration. Arabic music uses maqam modal scales. Words: habibi/habibti (my love), albi (my heart), ain (eye), shams (sun), leila (night), wein (where), rohi (my soul), enta/enti (you), ana (I). Ornamental vocal runs are central to Arabic style.", exampleCodemix: "Habibi albi kello lak, you have my whole heart, ma baada gheirak" },
  { name: "Korean", nativeScript: "Hangul", aceSupportTier: "primary", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "ace-step", syllableDensity: 0.9, codemixPartners: ["English"], associatedGenres: ["K-Pop", "Korean R&B", "Korean Hip Hop"], lyricsPromptInstruction: "Write primarily in Korean using romanized transliteration only — no actual Hangul characters. Korean-English codemixing is standard in K-pop. Common words: saranghae (I love you), nae maeum (my heart), gateun (same), honja (alone), bimil (secret), haengbok (happy), kkum (dream), nunmul (tears). At least 60% Korean phonetically.", exampleCodemix: "Nae maeum gipeun gose where only you exist, saranghae baby" },
  { name: "Japanese", nativeScript: "Hiragana / Katakana / Kanji", aceSupportTier: "primary", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "ace-step", syllableDensity: 1.5, codemixPartners: ["English"], associatedGenres: ["J-Pop", "Anime", "City Pop", "Japanese Rock"], lyricsPromptInstruction: "Write primarily in Japanese using romaji only — no Hiragana, Katakana, or Kanji. Japanese pop naturally includes English phrases. Common words: kokoro (heart), ai (love), yume (dream), sora (sky), kioku (memory), kimi (you), boku (I), hikari (light), kaze (wind). Every syllable has equal length.", exampleCodemix: "Kimi no koe ga kikitakute, calling out your name, kokoro ga tomaranai" },
  { name: "Mandarin", nativeScript: "Simplified Chinese characters", aceSupportTier: "primary", minimaxSupport: true, elevenLabsMultilingualSupport: true, preferredPath: "ace-step", syllableDensity: 0.8, codemixPartners: ["English"], associatedGenres: ["Mandopop", "Chinese R&B", "Chinese Hip Hop"], lyricsPromptInstruction: "Write primarily in Mandarin using pinyin romanization only — no Chinese characters. Mandopop naturally includes English phrases. Common words: wo ai ni (I love you), xin (heart), meng (dream), yue liang (moon), ni de (your), mei li (beautiful), yong yuan (forever).", exampleCodemix: "Wo ai ni baby, ni de xiao rong rang wo kai xin, can't stop thinking about you" },
  { name: "English", nativeScript: "Latin alphabet", aceSupportTier: "primary", minimaxSupport: true, elevenLabsMultilingualSupport: true, preferredPath: "elevenlabs-music", syllableDensity: 1.0, codemixPartners: [], associatedGenres: ["Pop", "Rock", "Hip Hop", "R&B", "Country", "EDM", "Metal"], lyricsPromptInstruction: "Write in standard English. Match vocabulary and slang to the genre: Hip Hop uses AAVE and street vernacular; Pop uses accessible emotional language; Country uses rural Southern imagery; Metal uses dark powerful imagery; R&B uses sensual intimate language; Folk uses literary storytelling.", exampleCodemix: "Standard English — no codemixing needed unless genre-specific slang" },
  { name: "Spanish", nativeScript: "Latin alphabet", aceSupportTier: "primary", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "elevenlabs-music", syllableDensity: 1.2, codemixPartners: ["English"], associatedGenres: ["Latin Pop", "Reggaeton", "Salsa", "Bachata", "Flamenco"], lyricsPromptInstruction: "Write primarily in Spanish. Spanglish codemixing is natural in reggaeton and Latin urban genres. Pure Spanish is preferred for salsa, flamenco, and romantic ballads.", exampleCodemix: "Tu eres mi vida entera, you know I need you, no puedo vivir sin ti" },
  { name: "French", nativeScript: "Latin alphabet", aceSupportTier: "primary", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "elevenlabs-music", syllableDensity: 1.2, codemixPartners: ["English"], associatedGenres: ["French Pop", "Chanson", "French Hip Hop", "Electronic"], lyricsPromptInstruction: "Write primarily in French. French music values beautiful phrasing. French hip hop commonly mixes with English. French chansons are poetic and literary.", exampleCodemix: "Je t'aime comme le soleil, you light up my world, sans toi je suis perdu" },
  { name: "Portuguese", nativeScript: "Latin alphabet", aceSupportTier: "supported", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "elevenlabs-music", syllableDensity: 1.2, codemixPartners: ["English", "Spanish"], associatedGenres: ["Bossa Nova", "Sertanejo", "Funk Carioca", "Brazilian Pop"], lyricsPromptInstruction: "Write in Portuguese. Use Brazilian Portuguese for sertanejo, funk carioca, and Brazilian pop. Bossa nova lyrics are poetic and understated.", exampleCodemix: "Meu amor, meu coração, you are everything to me, sem você não vivo" },
  { name: "German", nativeScript: "Latin alphabet", aceSupportTier: "supported", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "elevenlabs-music", syllableDensity: 0.9, codemixPartners: ["English"], associatedGenres: ["Schlager", "German Hip Hop", "Neue Deutsche Welle"], lyricsPromptInstruction: "Write in German. German compound words and strong consonants create unique rhythmic possibilities. German hip hop (Deutschrap) is very popular.", exampleCodemix: "Mein Herz schlägt nur für dich, you are my everything, ich liebe dich so sehr" },
  { name: "Italian", nativeScript: "Latin alphabet", aceSupportTier: "supported", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "elevenlabs-music", syllableDensity: 1.3, codemixPartners: ["English"], associatedGenres: ["Italian Pop", "Cantautore", "Italian Opera", "Italian Rock"], lyricsPromptInstruction: "Write in Italian. Italian is vowel-rich and naturally musical. Italian pop values romance and poetic imagery.", exampleCodemix: "Amore mio, sei il mio sole, you make me feel alive, voglio stare con te" },
  { name: "Turkish", nativeScript: "Latin alphabet (modern Turkish)", aceSupportTier: "supported", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "elevenlabs-music", syllableDensity: 1.0, codemixPartners: ["English"], associatedGenres: ["Turkish Pop", "Arabesk", "Turkish Hip Hop", "Turkish Folk"], lyricsPromptInstruction: "Write in Turkish. Words: seni seviyorum (I love you), kalbim (my heart), gözlerin (your eyes), aşk (love), güze (beautiful), gece (night), sensiz (without you).", exampleCodemix: "Seni seviyorum canım, you are everything, kalbim sadece senin için" },
  { name: "Russian", nativeScript: "Cyrillic", aceSupportTier: "supported", minimaxSupport: false, elevenLabsMultilingualSupport: true, preferredPath: "ace-step", syllableDensity: 0.9, codemixPartners: ["English"], associatedGenres: ["Russian Pop", "Russian Hip Hop", "Russian Electronic"], lyricsPromptInstruction: "Write in Russian using romanized transliteration — no Cyrillic. Words: lyubov (love), serdtse (heart), mechta (dream), noch (night), nebo (sky).", exampleCodemix: "Moya lyubov, ty moe serdtse, you are my everything, ne mogu bez tebya" },
  { name: "Yoruba", nativeScript: "Latin alphabet (tonal)", aceSupportTier: "limited", minimaxSupport: false, elevenLabsMultilingualSupport: false, preferredPath: "limited", syllableDensity: 1.1, codemixPartners: ["English", "Pidgin"], associatedGenres: ["Afrobeats", "Fuji", "Juju", "Afropop"], lyricsPromptInstruction: "Write in Yoruba with natural English and Nigerian Pidgin codemixing. Words: ife (love), opolopo (plenty), awa (we), ire (good things), ore mi (my friend), ololufe (beloved).", exampleCodemix: "Ife mi, you are my everything, awa go dance all night, ire ni o" },
  { name: "Swahili", nativeScript: "Latin alphabet", aceSupportTier: "limited", minimaxSupport: false, elevenLabsMultilingualSupport: false, preferredPath: "limited", syllableDensity: 1.2, codemixPartners: ["English"], associatedGenres: ["Bongo Flava", "East African Pop", "Afrobeats"], lyricsPromptInstruction: "Write in Swahili with natural English codemixing. Words: nakupenda (I love you), moyo (heart), usiku (night), ndoto (dream), rafiki (friend), nzuri (good/beautiful).", exampleCodemix: "Nakupenda sana baby, moyo wangu ni wako, you make me complete" },
];

export function findLanguage(name: string): LanguageDefinition | null {
  return LANGUAGE_DATABASE.find(l => l.name.toLowerCase() === name.toLowerCase()) ?? null;
}

export function getLyricsInstruction(language: string, description: string): string {
  return findLanguage(language)?.lyricsPromptInstruction ?? `Write lyrics primarily in ${language}. Respect natural rhythm, vocabulary, and musical conventions of ${language} popular music. Do not substitute English.`;
}

export function LANGUAGE_NAMES(): string[] { return LANGUAGE_DATABASE.map(l => l.name); }

export function getVocalQualityAdvisory(language: string): string | null {
  const lang = findLanguage(language);
  if (!lang) return null;
  if (language.toLowerCase() === "punjabi") {
    return "Punjabi vocals are best on the ElevenLabs-backed TTS mix path for clearer pronunciation and higher consistency.";
  }
  if (lang.preferredPath === "limited") return `${language} has limited AI vocal support. Instrumental mode recommended for best results.`;
  if (lang.preferredPath === "tts-mix") return `${language} uses dedicated vocal synthesis for best pronunciation. Generation takes 60-90 seconds.`;
  return null;
}
